version: '3.8'
services:
  todo-app:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://todo-db:5432/todo
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - todo-db

  todo-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"